FROM python:3.13-slim
WORKDIR /app
# Create a non-root user to run the application
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

# Install watchfiles for auto-reloading during development
COPY src/core_api/core_req.txt ./src/core_api/core_req.txt
COPY src/packages/shared_worker_library ./src/packages/shared_worker_library

# Install dependencies
RUN pip install --no-cache-dir -r src/core_api/core_req.txt
RUN pip install -e src/packages/shared_worker_library

# Copy application code
COPY . .

# Change ownership of the application directory to the non-root user
RUN chown -R appuser:appgroup /app
USER appuser

# run the application
CMD ["uvicorn", "src.core_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
