FROM python:3.13-slim
WORKDIR /app

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser

COPY src/coordinator/coord_req.txt ./src/coordinator/coord_req.txt
COPY src/packages/shared_worker_library ./src/packages/shared_worker_library

RUN pip install --no-cache-dir -r src/coordinator/coord_req.txt
RUN pip install -e src/packages/shared_worker_library

COPY . .

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["uvicorn", "src.coordinator.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
